version: 0.2

# AWS CodeBuild specification for building URBARN Android APK
# This allows you to build the APK using your AWS account instead of GitHub Actions

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing system dependencies..."
      - apt-get update -qq
      - apt-get install -y --no-install-recommends 
          build-essential git zlib1g-dev python3-dev 
          libffi-dev libssl-dev libbz2-dev libreadline-dev 
          libsqlite3-dev libncurses5-dev libgdbm-dev 
          openjdk-8-jdk unzip wget
      - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      - echo "Installing Python dependencies..."
      - python -m pip install --upgrade pip setuptools wheel
      - pip install buildozer cython kivy
      - pip install bleak cryptography
      
  pre_build:
    commands:
      - echo "Preparing build environment..."
      - ls -la
      - echo "Setting up buildozer cache..."
      - mkdir -p ~/.buildozer
      
  build:
    commands:
      - echo "Building URBARN APK with buildozer..."
      - echo "This will take 15-20 minutes on first build (downloading Android SDK/NDK)..."
      - yes | buildozer android debug
      - echo "APK build completed!"
      
  post_build:
    commands:
      - echo "Build finished. Checking output..."
      - ls -la bin/
      - echo "Uploading APK artifacts..."
      
artifacts:
  files:
    - 'bin/*.apk'
  name: urbarn-light-controller-apk-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - '/root/.buildozer/**/*'
    - '/root/.gradle/**/*'
    - '/root/.android/**/*'
